<Project>

  <!-- MSTest settings -->
  <PropertyGroup>
    <MSTestAnalysisMode>Recommended</MSTestAnalysisMode>
  </PropertyGroup>

  <!-- xUnit settings -->
  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Testing.Common'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)Testing.Common\Testing.Common.csproj">
      <IsAspireProjectResource>false</IsAspireProjectResource>
    </ProjectReference>
  </ItemGroup>

</Project>