<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Coupon.Domain\Coupon.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Coupon.UnitTests" />
    <InternalsVisibleTo Include="Coupon.API" />
  </ItemGroup>

</Project>
